const PAGE_NAMES = {
  PURCHASE_SUMMARY: 'PURCHASE_SUMMARY',
  PAYMENT_INSTRUCTIONS: 'PAYMENT_INSTRUCTIONS',
  UPLOAD_RECEIPT: 'UPLOAD_RECEIPT',
  CONFIRMATION_OF_RECEIPT: 'CONFIRMATION_OF_RECEIPT',
};
export default PAGE_NAMES;
